project_name: solarview

builds:
  - id: solarview
    main: ./main.go
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
#      - arm64
    ldflags:
      - -s -w

archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

release:
  github:
    owner: your-github-username
    name: solarview-go

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
