name: Build & Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch: # 支持手动触发

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean

      - name: Upload Artifacts (fallback)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-failure-artifacts
          path: dist/*
